// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZPgsVViovb0i3wAzwpz5pWs7w38lRAYA',
    appId: '1:406873283471:web:185870ac7fa7bee48509fa',
    messagingSenderId: '406873283471',
    projectId: 'deepklarity-store-listings',
    authDomain: 'deepklarity-store-listings.firebaseapp.com',
    storageBucket: 'deepklarity-store-listings.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWG8YBKiSoIe76Dl_P8Z9PJfPk6qUT5eI',
    appId: '1:406873283471:android:eacff222486736788509fa',
    messagingSenderId: '406873283471',
    projectId: 'deepklarity-store-listings',
    storageBucket: 'deepklarity-store-listings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM-dGj5874FbmtY-XG7WINUiPp7abLbQI',
    appId: '1:406873283471:ios:5e15372bf5c6d27d8509fa',
    messagingSenderId: '406873283471',
    projectId: 'deepklarity-store-listings',
    storageBucket: 'deepklarity-store-listings.appspot.com',
    iosClientId: '406873283471-r5cvcafmu5bbp13rnj1h4p27kpitqrgr.apps.googleusercontent.com',
    iosBundleId: 'com.abdullahmeda.storeListings',
  );
}
